import { mkdirSync, writeFileSync, rmSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { homedir } from "node:os";
import { execSync, spawn } from "node:child_process";

const CONFIG_DIR = join(homedir(), ".config", "dia-sidepanel-patcher");
const LAUNCHER_PATH = join(CONFIG_DIR, "launcher.sh");
const PLIST_PATH = join(homedir(), "Library", "LaunchAgents", "com.dia-sidepanel-patcher.plist");
const LOG_PATH = "/tmp/dia-sidepanel-patcher.log";
const LABEL = "com.dia-sidepanel-patcher";

function getBinaryPath(): string {
  try {
    return execSync("which dia-sidepanel-patcher", { encoding: "utf-8" }).trim();
  } catch {
    return resolve(process.argv[1]);
  }
}

function generateLauncher(binaryPath: string, port: number): string {
  return `#!/bin/bash
# Generated by dia-sidepanel-patcher install

# Source shell profile to get PATH (nvm, brew, volta, etc.)
[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc" 2>/dev/null
[ -f "$HOME/.bash_profile" ] && source "$HOME/.bash_profile" 2>/dev/null

PORT=${port}
DIA="/Applications/Dia.app/Contents/MacOS/Dia"

pkill -f "dia-sidepanel-patcher" 2>/dev/null

# If Dia is running without CDP, quit and relaunch
if pgrep -x Dia >/dev/null && ! curl -s "http://127.0.0.1:$PORT/json/version" >/dev/null 2>&1; then
  osascript -e 'tell application "Dia" to quit' 2>/dev/null
  # Wait until Dia is fully gone
  for i in $(seq 1 20); do
    pgrep -x Dia >/dev/null || break
    sleep 0.5
  done
  sleep 1
fi

# Only launch if Dia isn't already running with CDP
if ! curl -s "http://127.0.0.1:$PORT/json/version" >/dev/null 2>&1; then
  "$DIA" --remote-debugging-port=$PORT &
fi

for i in $(seq 1 30); do
  curl -s "http://127.0.0.1:$PORT/json/version" >/dev/null 2>&1 && break
  sleep 0.5
done

exec "${binaryPath}" --port $PORT >> "${LOG_PATH}" 2>&1
`;
}

function generatePlist(): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${LAUNCHER_PATH}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <false/>
    <key>StandardOutPath</key>
    <string>${LOG_PATH}</string>
    <key>StandardErrorPath</key>
    <string>${LOG_PATH}</string>
</dict>
</plist>`;
}

export function isInstalled(): boolean {
  return existsSync(PLIST_PATH);
}

export function install(port: number = 9222): void {
  if (isInstalled()) {
    console.log("Already installed. Run 'dia-sidepanel-patcher uninstall' first.");
    return;
  }

  const binaryPath = getBinaryPath();

  mkdirSync(CONFIG_DIR, { recursive: true });
  writeFileSync(LAUNCHER_PATH, generateLauncher(binaryPath, port), { mode: 0o755 });
  console.log("  ✓ Created launcher script");

  writeFileSync(PLIST_PATH, generatePlist());
  console.log("  ✓ Created LaunchAgent (auto-starts on login)");

  // Activate now — restart Dia with CDP and start the patcher in background
  console.log("  ⟳ Starting Dia with debugging enabled...");
  const child = spawn("bash", [LAUNCHER_PATH], {
    detached: true,
    stdio: "ignore",
  });
  child.unref();

  console.log(`\n  Auto-start installed. Logs: ${LOG_PATH}`);
  console.log("  To remove: dia-sidepanel-patcher uninstall");
}

export function uninstall(): void {
  if (!isInstalled()) {
    console.log("Not installed.");
    return;
  }

  try {
    execSync(`launchctl unload "${PLIST_PATH}" 2>/dev/null`);
  } catch { /* may already be unloaded */ }

  rmSync(PLIST_PATH, { force: true });
  rmSync(CONFIG_DIR, { recursive: true, force: true });

  console.log("  ✓ Removed LaunchAgent and config");
  console.log("Auto-start uninstalled.");
}

export function status(): void {
  if (isInstalled()) {
    console.log("Installed: auto-start is active");
    console.log(`  LaunchAgent: ${PLIST_PATH}`);
    console.log(`  Launcher: ${LAUNCHER_PATH}`);
    console.log(`  Logs: ${LOG_PATH}`);
  } else {
    console.log("Not installed. Run 'dia-sidepanel-patcher install' to auto-start with Dia.");
  }
}
